[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Single-page app routing (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
